

function VigenerePage() {
    return (
        <div>
            <h1>Vigenere Cipher</h1>
            <p>The Vigenère cipher is a method of encrypting alphabetic text by using a simple form of polyalphabetic substitution. A polyalphabetic cipher uses multiple substitution alphabets to encrypt the data. The Vigenère cipher has been reinvented many times. The method was originally described by Giovan Battista Bellaso in his 1553 book La cifra del. Sig. Giovan Battista Bellaso; however, the scheme was later misattributed to Blaise de Vigenère in the 19th century, and is now widely known as the "Vigenère cipher".</p>
            <p>The Vigenère cipher is easy to understand and implement, but it resisted all attempts to break it for three centuries, earning it the description le chiffre indéchiffrable (French for 'the indecipherable cipher'). Many people have tried to implement the Vigenère cipher, but most of them failed to do so. The Vigenère cipher is simple to understand and implement, but it is also very difficult to break. The Vigenère cipher is a method of encrypting alphabetic text by using a simple form of polyalphabetic substitution. A polyalphabetic cipher uses multiple substitution alphabets to encrypt the data. The Vigenère cipher has been reinvented many times. The method was originally described by Giovan Battista Bellaso in his 1553 book La cifra del. Sig. Giovan Battista Bellaso; however, the scheme was later misattributed to Blaise de Vigenère in the 19th century, and is now widely known as the "Vigenère cipher".</p>
            <h1>Vigenere Cipher</h1>
            <p>The Vigenère cipher is a method of encrypting alphabetic text by using a simple form of polyalphabetic substitution. A polyalphabetic cipher uses multiple substitution alphabets to encrypt the data. The Vigenère cipher has been reinvented many times. The method was originally described by Giovan Battista Bellaso in his 1553 book La cifra del. Sig. Giovan Battista Bellaso; however, the scheme was later misattributed to Blaise de Vigenère in the 19th century, and is now widely known as the "Vigenère cipher".</p>
            <p>The Vigenère cipher is easy to understand and implement, but it resisted all attempts to break it for three centuries, earning it the description le chiffre indéchiffrable (French for 'the indecipherable cipher'). Many people have tried to implement the Vigenère cipher, but most of them failed to do so. The Vigenère cipher is simple to understand and implement, but it is also very difficult to break. The Vigenère cipher is a method of encrypting alphabetic text by using a simple form of polyalphabetic substitution. A polyalphabetic cipher uses multiple substitution alphabets to encrypt the data. The Vigenère cipher has been reinvented many times. The method was originally described by Giovan Battista Bellaso in his 1553 book La cifra del. Sig. Giovan Battista Bellaso; however, the scheme was later misattributed to Blaise de Vigenère in the 19th century, and is now widely known as the "Vigenère cipher".</p>
            <h1>Vigenere Cipher</h1>
            <p>The Vigenère cipher is a method of encrypting alphabetic text by using a simple form of polyalphabetic substitution. A polyalphabetic cipher uses multiple substitution alphabets to encrypt the data. The Vigenère cipher has been reinvented many times. The method was originally described by Giovan Battista Bellaso in his 1553 book La cifra del. Sig. Giovan Battista Bellaso; however, the scheme was later misattributed to Blaise de Vigenère in the 19th century, and is now widely known as the "Vigenère cipher".</p>
            <p>The Vigenère cipher is easy to understand and implement, but it resisted all attempts to break it for three centuries, earning it the description le chiffre indéchiffrable (French for 'the indecipherable cipher'). Many people have tried to implement the Vigenère cipher, but most of them failed to do so. The Vigenère cipher is simple to understand and implement, but it is also very difficult to break. The Vigenère cipher is a method of encrypting alphabetic text by using a simple form of polyalphabetic substitution. A polyalphabetic cipher uses multiple substitution alphabets to encrypt the data. The Vigenère cipher has been reinvented many times. The method was originally described by Giovan Battista Bellaso in his 1553 book La cifra del. Sig. Giovan Battista Bellaso; however, the scheme was later misattributed to Blaise de Vigenère in the 19th century, and is now widely known as the "Vigenère cipher".</p>
            <h1>Vigenere Cipher</h1>
            <p>The Vigenère cipher is a method of encrypting alphabetic text by using a simple form of polyalphabetic substitution. A polyalphabetic cipher uses multiple substitution alphabets to encrypt the data. The Vigenère cipher has been reinvented many times. The method was originally described by Giovan Battista Bellaso in his 1553 book La cifra del. Sig. Giovan Battista Bellaso; however, the scheme was later misattributed to Blaise de Vigenère in the 19th century, and is now widely known as the "Vigenère cipher".</p>
            <p>The Vigenère cipher is easy to understand and implement, but it resisted all attempts to break it for three centuries, earning it the description le chiffre indéchiffrable (French for 'the indecipherable cipher'). Many people have tried to implement the Vigenère cipher, but most of them failed to do so. The Vigenère cipher is simple to understand and implement, but it is also very difficult to break. The Vigenère cipher is a method of encrypting alphabetic text by using a simple form of polyalphabetic substitution. A polyalphabetic cipher uses multiple substitution alphabets to encrypt the data. The Vigenère cipher has been reinvented many times. The method was originally described by Giovan Battista Bellaso in his 1553 book La cifra del. Sig. Giovan Battista Bellaso; however, the scheme was later misattributed to Blaise de Vigenère in the 19th century, and is now widely known as the "Vigenère cipher".</p>
            <h1>Vigenere Cipher</h1>
            <p>The Vigenère cipher is a method of encrypting alphabetic text by using a simple form of polyalphabetic substitution. A polyalphabetic cipher uses multiple substitution alphabets to encrypt the data. The Vigenère cipher has been reinvented many times. The method was originally described by Giovan Battista Bellaso in his 1553 book La cifra del. Sig. Giovan Battista Bellaso; however, the scheme was later misattributed to Blaise de Vigenère in the 19th century, and is now widely known as the "Vigenère cipher".</p>
            <p>The Vigenère cipher is easy to understand and implement, but it resisted all attempts to break it for three centuries, earning it the description le chiffre indéchiffrable (French for 'the indecipherable cipher'). Many people have tried to implement the Vigenère cipher, but most of them failed to do so. The Vigenère cipher is simple to understand and implement, but it is also very difficult to break. The Vigenère cipher is a method of encrypting alphabetic text by using a simple form of polyalphabetic substitution. A polyalphabetic cipher uses multiple substitution alphabets to encrypt the data. The Vigenère cipher has been reinvented many times. The method was originally described by Giovan Battista Bellaso in his 1553 book La cifra del. Sig. Giovan Battista Bellaso; however, the scheme was later misattributed to Blaise de Vigenère in the 19th century, and is now widely known as the "Vigenère cipher".</p>
        </div>
    )
}

export default VigenerePage;